#!/usr/bin/env python
# -*- coding: utf-8 -*-

import math
import random
from pprint import pprint

SEED = 69
LIMIT = 10000

POPULATION_TOTAL = 7721989320
POPULATION_INFECTED = 0
POPULATION_DEAD = 0
BIRTH_RATE = min(1 / random.randint(2, LIMIT*10), 0.000002)

random.seed(SEED)
SEVERITY = min(1 / random.randint(2, LIMIT), 0.0002)  # detection rate
LETHALITY = min(1 / random.randint(2, LIMIT), 0.0002)  # rate of population decrease
INFECTIVITY = min(1 / random.randint(2, LIMIT*10), 0.000002)  # rate of infection

print("INFECTIVITY", INFECTIVITY)
print("LETHALITY", LETHALITY)
print("SEVERITY", SEVERITY)
# (LETHALITY * INFECTIVITY) + (SEVERITY * LETHALITY) + (SEVERITY * INFECTIVITY)
CURE = 0.0
CURE_THRESHOLD = min(math.ceil(POPULATION_TOTAL * SEVERITY), LIMIT * LIMIT)

pprint(globals())

while (POPULATION_DEAD + POPULATION_INFECTED) < POPULATION_TOTAL and CURE < 100:

    POPULATION_TOTAL += math.ceil(POPULATION_TOTAL * BIRTH_RATE)
    POPULATION_DEAD += math.ceil(POPULATION_INFECTED * LETHALITY * SEVERITY)
    POPULATION_INFECTED += math.ceil((POPULATION_TOTAL - POPULATION_DEAD) * INFECTIVITY)
    if (POPULATION_DEAD + POPULATION_INFECTED) >= POPULATION_TOTAL:
        break
    INFECTIVITY += 0.000001
    LETHALITY += 0.0000005
    # print(LETHALITY)
    if POPULATION_INFECTED <= CURE_THRESHOLD:
        print(POPULATION_INFECTED, POPULATION_DEAD,POPULATION_TOTAL, CURE)
    else:
        CURE += 0.1
        print("CURE STARTED AT", POPULATION_INFECTED,POPULATION_DEAD, POPULATION_TOTAL, CURE)
    if str(LETHALITY)[-1] == "1":
        CURE = abs(CURE - 0.25)
        print("UH OH")
    if str(LETHALITY)[-1] == "2":
        INFECTIVITY = abs(INFECTIVITY - 0.0000005)
        print("YAY")


print("INFECTED", POPULATION_INFECTED)
print("DEAD", POPULATION_DEAD)
print("TOTAL AFFECTED", POPULATION_INFECTED+POPULATION_DEAD)
print("HEALTHY", POPULATION_TOTAL-(POPULATION_INFECTED+POPULATION_DEAD))
print("ALIVE", POPULATION_TOTAL-POPULATION_DEAD)
print("HEALTHY", (POPULATION_TOTAL-(POPULATION_INFECTED+POPULATION_DEAD))/POPULATION_TOTAL*100)
